#baseURL = 'https://i14y-ch.github.io/handbook/'
languageCode = 'de-CH'
title = 'Handbuch Interoperabilitätsplattform I14Y'

# Language settings
contentDir = "content/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

# Language configuration
[languages]
[languages.de]
title = "Handbuch Interoperabilitätsplattform I14Y"
languageName = "Deutsch"
languageCode = "de"
contentDir = "content/de"
weight = 1

[languages.de.params]
description = "Anleitungen und Informationen zur Interoperabilitätsplattform"

[languages.fr]
title = "Manuel I14Y plateforme d’interopérabilité"
languageName = "Français"
languageCode = "fr"
contentDir = "content/fr"
weight = 2

[languages.fr.params]
description = "Instructions et informations sur la plate-forme d'interopérabilité"

[languages.it]
title = "Manuale I14Y piattaforma di interoperabilità"
languageName = "Italian"
languageCode = "it"
contentDir = "content/it"
weight = 3

[languages.it.params]
description = "Guida e informazioni sulla piattaforma di interoperabilità"

# [languages.rm]
# title = "Manual da plattafurma d'interoperabilitad I14Y"
# description = ""
# languageName = "Rumantsch"
# languageCode = "rm"
# contentDir = "content/rm"
# weight = 4

[languages.en]
title = "Manual I14Y Interoperability Platform"
languageName = "English"
languageCode = "en"
contentDir = "content/en"
weight = 5

[languages.en.params]
description = "Manual and Information about the interoperability platform"

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.121.1"  # Aktuelle stabile Version statt bleeding edge
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true

# Konfiguration für den Diagramm-Generator Mermaid.
[params.mermaid]
enable = true
theme = "default"
version = "11.4.1"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true
